version: "3"

services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_LOCATION: file:///run/secrets/hapi_application.yaml
    secrets:
      - source: hapi_application.yaml
    # configs:
    #   - source: hapi
    #     target: /app/config/application.yaml
    networks:
      - internal

  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    networks:
      - internal
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs 
    networks:
      - internal

# configs:
#   hapi:
#      file: ./configs/hapi_application.yaml

secrets:
  hapi_application.yaml:
    file: ./configs/hapi_application.yaml 

volumes:
  hapi-fhir-postgres:

networks:
  internal:
    driver: bridge
